src/cs2610project/blog/urls.py
from django.urls import path

from . import views

app_name='blog'
urlpatterns = [
    path('bio', views.bio, name='bio'),
    path('tips', views.tips, name='tips'),
    path('', views.index, name='index'),
    path('bloghome',views.BlogHome, name ='bloghome'),
    path('<int:b_id>/postComment', views.postComment, name = 'postComment'),
    path('blogarchive',views.BlogArchive, name ='archive'),
    path('<int:b_id>',views.BlogEntry, name ='entry'),
    path('nuke', views.nuke, name = 'nuke'),
    path('init', views.init,name = 'init' ),
]

src/cs2610project/cs2610project/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('blog/', include('blog.urls')),
    path('admin/', admin.site.urls),
]

src/cs2610project/blog/models.py
from django.db import models
from django.utils import timezone

# Create your models here.
class Blog(models.Model):
    title = models.CharField(max_length = 200)
    author_name = models.CharField(max_length = 200)
    content = models.CharField(max_length = 3000)
    post_date = models.DateTimeField('date posted')

class Comment(models.Model):
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE)
    nickname = models.CharField(max_length = 200)
    email = models.CharField(max_length = 200)
    content = models.CharField(max_length = 3000)
    post_date = models.DateTimeField('date posted')

src/cs2610project/blog/templates/blog/BlogArchive.html
<!DOCTYPE html>
<html lang="en">
{%load static %}
  <head>
     <meta charset="utf-8"/>
     <title>Archive</title>

     <link rel="stylesheet" type="text/css" href="{% static 'blog/shared.css' %}">
  </head>
  <body class = "bg-dark text-white">
      <ul>
      <li><a href="{% url 'blog:bloghome'%}">Home</a></li>
    </ul>

  	{% if last %}
  		{% for blog in last %}
    		<h1><a href="{% url 'blog:entry' blog.id %}">{{ blog.title }}</a></h1>
    		<div>{{blog.post_date}}</div>
    		<p>{{blog.content|truncatewords:200}}</p>
    		<div>There are{{blog.comment_set.count}} comments </div>
  		{% endfor %}
	  {% else %}
  		<h1>No more blogs</h1>
		{% endif %}
  </body>
</html>

src/cs2610project/blog/templates/blog/BlogEntry.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
  <head>
     <meta charset="utf-8"/>
     <title>Entry</title>
     <link rel="stylesheet" type="text/css" href="{% static 'blog/shared.css' %}">
     
  </head>
  <body class ="bg-dark text-white">
      <ul>
      <li><a href="{% url 'blog:archive'%}">Archive</a></li>
      <li><a href="{% url 'blog:bloghome'%}">Home</a></li>
    </ul>

  	<h1>{{blog.title}}</h1>
  	<div>{{blog.authorname}} -- {{blog.post_date}}</div>
  	<p>{{ blog.content}}</p>

  	{% for comment in blog.comment_set.all %}
  	<dir>{{ comment.nickname }} -- {{comment.email}} -- {{comment.post_date}}</dir>
  	<p>{{ comment.content }}</p>
  	{% endfor %}

  	<form action = "{% url 'blog:postComment' blog.id %}" method="POST">
  	{%csrf_token %}
  	<header>
  		<h2>Post Comment</h2>
  	</header>
  	<div> 
  		<label for="nickname">Nickname:</label>
  		<input type="text" id="nickname" name="nickname">

  		<label for="email">Email:</label>
  		<input type="email" id="email" name="email">
  	</div>
  	<div>
  		<label for="content">Comment:</label>
  		<textarea id ="content" name="content"></textarea>
  	</div>
  	<div>
  		<button id="submission" type="submit">Submit Comment</button>
  	</div>
  </form>
  </body>
</html>

src/cs2610project/blog/templates/blog/BlogHome.html
<!DOCTYPE html>
<html lang="en">
{%load static %}
  <head>
     <meta charset="utf-8"/>
     <title>Blog Home</title>
       
     <link rel="stylesheet" type="text/css" href="{% static 'blog/shared.css' %}">
  </head>
  <body class = "bg-dark text-white">
     <ul>
      <li><a href="{% url 'blog:archive'%}">Archive</a></li>
          </ul>
  	{% if last %}
  		{% for blog in last %}
        <h1><a href="{% url 'blog:entry' blog.id %}">{{ blog.title }}</a></h1>
    		<div>{{blog.post_date}}</div>
    		<p>{{blog.content|truncatewords:200}}</p>
    		<div>There are{{blog.comment_set.count}} comments </div>
  		{% endfor %}
		{% else %}
  		<h1>No more blogs</h1>
		{% endif %}
  </body>
</html>

src/cs2610project/blog/templates/blog/Tips.html
<!DOCTYPE html>
<html lang="en">
 {% load static %}
  <head>
    <link rel="stylesheet" type="text/css" href="{% static 'blog/shared.css'%}">
     <meta charset="utf-8"/>
     <title>Tips</title>
     <style> 
     table 
     {
      text-align: center;
     }
     .git, .git td, .git th{
      border: solid;
      border-color: #8fd639;
     }


     

       </style>
   <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity ="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS"
   crossorigin="anonymous">

  </head>
  <body class ="bg-dark text-white">
    <h1 id="main">Tips</h1>
  	<ul>
      <li><a href="{% url 'blog:bio'%}">Bio</a></li>
      <li><a href="{% url 'blog:index'%}">Blog</a></li>
    </ul>

  	<h1>Tips</h1>


  	<table class="git">
  		<thead>
  			<tr>
  				
  				<th>Command</th>
  				<th>Description</th>
  				<th>Example</th>
  			</tr>
  		</thead>
  		<tbody>
  			<tr>
  				<td>Git rm</td>
  				<td>Remove item from repo</td>
  				<td><code>git rm file.txt</code></td>
  			</tr>
  		</tbody>

  	</table>
    <p>

 {{now}}
 
</p>

  </body>
</html>

src/cs2610project/blog/templates/blog/bio.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
  <head>
    <link rel="stylesheet" type="text/css" href="{% static 'blog/shared.css'%}">

     <meta charset="utf-8"/>
     <title>Bio</title>
  <style> 
   
     div {
  margin-top: 75px;
  margin-bottom: 75px;
  margin-right: 125px;
  margin-left: 65px;
}
   </style>
   <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity ="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS"
   crossorigin="anonymous">



     </head>
  <body class="bg-dark text-white">

  	<h1 id= "main">Bio</h1>
  	 	<ul>
      <li><a href="{% url 'blog:tips'%}">Tips</a></li>
      <li><a href="{% url 'blog:index'%}">Blog</a></li>
    </ul>

  	<img src="{% static "blog/images/sheep.jpg" %}" alt="sheep"/>

  	<div>
  		hey,
  		Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla accumsan ultricies leo sed efficitur. Aenean ac tincidunt augue. Vestibulum ut est posuere elit finibus elementum. Fusce venenatis eget dui nec sollicitudin. Donec tortor eros, elementum id nulla eu, fringilla pretium nisl. Donec ut felis ac velit tincidunt egestas. Nam a quam vel leo consequat condimentum id eget magna. Aenean congue arcu nunc, et pharetra arcu tempus vitae.
  	</div>

  <img src="{% static "blog/images/hockey.png" %}" alt="hockey"/>  	<div> Hockey </div>

  	<img src="{% static "blog/images/sky.jpg" %}" alt="sky"/>  	<div>Snow Boarding</div>


  	<img src="{% static "blog/images/board.jpg" %}" alt="board"/>
  	<div>Skydiving</div>

<p>

 {{now}}
 
</p>




  </body>
</html>

src/cs2610project/blog/templates/blog/blog.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
  <head>
    <link rel="stylesheet" type="text/css" href="{% static 'blog/shared.css'%}">

     <meta charset="utf-8"/>
     <title>Blog</title>

     <style> 

     div 
  {
      padding-top: 10px;
      padding-right: 0px;
      padding-bottom: 25px;
      padding-left: 10px;
}

p
{
      background-color: grey;
}  
 </style>

   <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity ="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS"
   crossorigin="anonymous">
  </head>
  <body class="bg-dark text-white">
    <h1 id="main">Blog</h1>

    <ul>
      <li><a href="{% url 'blog:bio'%}">Bio</a></li>
      <li><a href="{% url 'blog:tips'%}">Tips</a></li>
    </ul>

  	
  	<h2>Week</h2>

    <ol>

      <li>

  	<div>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent interdum consectetur sapien, in semper ex tincidunt ut. Integer in rhoncus metus. Donec porta velit id finibus pulvinar. Nulla elementum ante ut volutpat lobortis. Fusce eu maximus dolor, sed varius tellus. Aliquam erat volutpat. Nulla a mauris tristique, elementum tellus vitae, dapibus quam. Pellentesque vel nisl a orci sollicitudin fringilla eget et mi. Integer laoreet consectetur lacus. Nunc interdum auctor enim. Nam fermentum augue velit, quis feugiat lacus cursus id. Mauris mattis ornare nulla, sed commodo purus laoreet id. Pellentesque lorem nisl, convallis vel tortor non, sagittis tristique diam. Mauris et libero sed ipsum facilisis hendrerit. Integer nisi quam, lacinia non arcu id, scelerisque congue mi.</div>
  </li>

  <li>

  	<h2>Month</h2>
    <div>Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Praesent nec mi non lectus scelerisque luctus. Nulla interdum, nisl nec egestas dapibus, risus tellus ultricies turpis, at rutrum dolor tortor nec augue. Praesent porttitor tincidunt turpis, euismod tristique libero molestie ut. Aliquam sed sapien accumsan, malesuada mauris ut, mollis eros. Nullam eget pharetra dolor, eget congue nulla. Pellentesque velit felis, lacinia vel venenatis nec, scelerisque vel neque. Proin at urna tincidunt, pretium ex quis, venenatis orci. Pellentesque sed erat a nibh pulvinar semper non nec elit. Nunc mollis diam et nisi volutpat, non aliquet orci ullamcorper. Pellentesque imperdiet mauris tristique sapien imperdiet, vitae vehicula lectus convallis. Nulla fermentum felis sed turpis lacinia, vitae rhoncus purus porta.</div>

  </li>

<li>

  	<h2>Year</h2>

  	<p>Suspendisse potenti. Phasellus vitae tristique erat. Ut porttitor neque ut dolor efficitur, vel aliquet est sollicitudin. Nulla in nunc eget nulla tincidunt vestibulum quis ac ante. Vivamus felis sapien, rutrum ac ligula sit amet, euismod facilisis nunc. Aenean vestibulum velit id hendrerit hendrerit. In pulvinar mi vitae eleifend viverra. Vivamus imperdiet ligula fringilla augue accumsan, sed auctor elit consectetur. Quisque orci ex, porttitor a lorem in, varius mattis ex. Praesent faucibus id lectus ut euismod. Phasellus ex arcu, posuere ac sem in, hendrerit aliquet nibh. Maecenas eros enim, viverra ac dictum ut, fringilla eget massa. Cras lectus nunc, tincidunt at luctus sed, lacinia rutrum turpis.</p>

  </li>

</ol>

<p>

 {{now}}

</p>

  </body>
</html>